lib/ics.js
package.json

Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …

Update uuid to version 3.0.0

---

README.md
lib/ics.js
test/ics.spec.js

- Add support for a user generated UID. In order to cancel a previously created calendar event, you'll need to reference the UID.

Add support for custom uid

---

lib/ics.js
test/ics.spec.js

Reimplements the organizer field. Only allows one organizer as per [RFC 5545](https://tools.ietf.org/html/rfc5545#page-111). Fixes #23.

Reimplement organizer field

---

README.md

I made sure to include a warning about specifying your own _id.  My co-founder spent a few hours trying to modify the output with a regex because he didn't realize that you could directly pass in a `uid`.  Seemed worth documenting.

Updated README to reflect productId & uid options

---

src/pipeline/format.js
src/utils/set-description.js

Fixes #31 
Also escapes colons and semicolons because these are also reserved as part of the [iCalendar 2.0](https://tools.ietf.org/html/rfc5545) spec.
Thanks for the lovely library!

Sanitize description for newlines, colons, and semicolons

---

src/pipeline/format.js
src/utils/fold-line.js
src/utils/index.js
src/utils/set-alarm.js
test/pipeline/format.spec.js

This PR introduces a utility function called `foldLine` to address lines longer than 75 characters. See https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html.
`foldLine` is applied to formatting for all fields that I thought might overflow. The list of fields that get this treatment probably need review.
RFC2425 §5.8.2 states that parsers MUST unfold lines correctly:
```
; When parsing a content line, folded lines MUST first
; be unfolded according to the unfolding procedure
; described above.  When generating a content line, lines
; longer than 75 octets SHOULD be folded according to
; the folding procedure described above.
```
Potential risk: I don't know the state of most parsers out there, or if folding, say, a URL might confuse them.
I recall having trouble (I think on …

Fold lines longer than 75 characters to address #65

---

src/schema/index.js
src/utils/set-contact.js
src/utils/set-organizer.js
test/utils/set-contact.spec.js

This PR adds [DIR](https://www.kanzaki.com/docs/ical/dir.html) attribute into `organizer` and `attendees` (related to #86).

Allow DIR attribute into organizer and attendees

---

src/index.js
test/index.spec.js

I was asynchronously creating multiple instances of an ical using `createEvent` and when I tried to load them up as a test (one at a time) - each one created would make the first one flash as though it was already existing (even though each new event was unique) and not actually add that new event.
Digging in - I discovered that they all had the same UID.
Any thoughts on taking this PR to avoid this issue?
-- I ended up using `createEvents` in the end - but hopefully this PR helps the next one who tries what I did...

Create unique UID's for each time createEvent is called

---

README.md
package-lock.json
src/pipeline/format.js
src/schema/index.js
test/pipeline/format.spec.js

Using this library to create large calendars with >100 all-day events that recur for 80 years (crazy), and most people who use consume this calendar use Outlook. The default busy status for any event in outlook is `BUSY` which is problematic because it kills the Outlook functionality to check for availability. Therefore, I'm moving to add functionality to support for `X-MICROSOFT-CDO-BUSYSTATUS`

added functionality for `X-MICROSOFT-CDO-BUSYSTATUS`

---

README.md
index.d.ts

The alarm type values for `AlarmTypes` in `index.d.ts` should be lower case
```
Error [ValidationError]: child "alarms" fails because ["alarms" at position 0 fails because [child "action" fails because ["action" with value "DISPLAY" fails to match the required pattern: /audio|display|email/]]]
```

[CHORE] Add Correct AlarmType Values for Typescript

---

package-lock.json
package.json
src/schema/index.js
test/schema/index.spec.js

In order to have the library working in environments where `net` Node module is not available (such as browsers), `@hapi/joi` version got bumped to the latest version. This required also the following changes:
1. Change to how Joi's `validate` method is called, together with defaulting `error` to `null` to keep backwards compatibility.
1. Adjusting validation error messages, as they changed for array validation.
1. Disabling Joi's TLD validation for emails
Note: I haven't bumped `ics` version, as I saw it's already above latest available on NPM.

updates @hapi/joi to v17

---

src/utils/format-utc-date-as-utc.js

Format seconds rather than hardcoding `00`
closes #135

Format seconds

---

package-lock.json
package.json
src/pipeline/format.js
src/utils/set-alarm.js

`lodash` is included as a dependency for two very trivial purposes - it's unnecessary.
- `_.isEqual` was used to check that `start` and `end` arrays were unequal. `start.length !== end.length || start.some((val, i) => val !== end[i])` has the same effect.
- `_.isArray` is implemented by lodash with native `Array.isArray` wherever it is available anyway, which is [pretty much everywhere](https://caniuse.com/?search=Array.isArray). (This lib already uses `Object.assign`, which is [much newer](https://caniuse.com/?search=Object.assign))

Remove dependency on lodash

---

index.d.ts

- `created` and `lastModified` are available to be set in the config but they are not accounted for in the `EventAttributes` type.

Add created and lastModified to EventAttributes type

---

src/pipeline/build.js

lodash is removed in #150. But it is used in `pipeline/build.js`.
lodash is replaced by js native functions in this PR.
This PR resolves #154.

Replace lodash/pickBy in pipeline/build.js

---

package-lock.json
package.json
src/schema/index.js

Since @hapi/joi is [deprecated](https://www.npmjs.com/package/@hapi/joi). This also updates the version installed by npm to `17.3.0`, from `17.1.1`, because @hapi/joi has not been receiving updates since `17.1.1`. There was a [breaking change](https://github.com/sideway/joi/issues/2284) in `17.2.0` that was intentionally released in a minor version, with [this message](https://github.com/sideway/joi/issues/2284#issuecomment-653958119):
> I'm marking this as a breaking change (released as a non-breaking version) because it is possible someone has written an extension that uses this bug to send multiple errors from a custom rule using an array. If that's the case, this will break that because it now requires a special array generated by helpers.errorsArray(). Since this wasn't documented …

Dependencies: switch from @hapi/joi to joi

---

.gitignore
README.md
src/schema/index.js
src/utils/fold-line.js
src/utils/format-date.js
src/utils/set-alarm.js
test/pipeline/build.spec.js
test/pipeline/format.spec.js
test/schema/index.spec.js

* README.md
- Updated to include organizer.dir
* src\schema\index.js
- Updadet organizer schema to include dir
* src\utils\fold-line.js
- Changed approach from building an array that joins at the end, to a string concat approach, which is about 4 times faster, which seemed appropriate, for the function that is called the most.
* src\utils\format-date.js
- Extracted isArray() check to be only done once
* src\utils\set-alarm.js
- Swapped setDuration() function with formatDuration(), since it is duplicate code
* test\pipeline\build.spec.js
- Added dir attribute to the organizer objects
* test\pipeline\format.spec.js
- Added dir attribute to the organizer objects
* test\schema\index.spec.js
- Added dir attribute to the organizer objects
Issue that is being addressed: …

Added support for dir value for organizer - for PR 132

---

package-lock.json
package.json
src/schema/index.js
test/schema/index.spec.js

Rationale
@hapi/joi is huge and a significant download burden in the browser, see https://github.com/adamgibbons/ics/issues/149
Yup was designed to be a lightweight, browser friendly, alternative to @hapi/joi, its interface is pretty similar, this did make the transition substantially easier.  I'll admit I have a bias, I use yup all over the place already so I didn't look at alternatives.
There are at least two issues associated with this PR.
1. I picked yum, this suits me, is much smaller than joi and is functionally sufficient for the project.  But it's likely that this choice won't satisfy everyone.
2. This substantially changes the error reporting from validateEvent, that ripples up through the api and is in turn exposed as the error object from createEvents.  You can see that nearly …

Convert validation from joi to yup

---

README.md

In trying to diagnose an issue with why our ICS files were not being
validated correctly on iCalendar Validator due to a missing
'DESCRIPTION' within 'VALARM', I came across the ticket
from YM-KA stating that you could add the description field to the
alarms object without issue. I ran across in an iCalendar spec that the
description is one of three required fields for it to be valid as well,
so I thought that the README and it's examples regarding alarms should
reflect that, as there is currently no documentation of the description
field at all.  This would have saved me some time and hopefully will save
others the same fruustration.
This PR adds a `description` field to all instances of the `alarms`
array and the objects contained within.

Add `description` field to `alarms` examples

---

src/schema/index.js

The yup error object is a javascript Error which in turn makes logging
it a bit limiting, the stack trace gets dumped and the useful error
information is hidden.  It's still there, but it's presence isn't
obvious to the user, and this in turn limits its usability.
By cloning the fields over to a new object the same data remains but the
logging is improved and the behavior become more in line with that of
the joi version.

fix error object

---

package-lock.json
package.json
src/defaults.js
src/index.js

`uuid` is bigger than `nanoid` and ics is also using an old release of `uuid`. Instead of upgrading uuid (that is currently showing a scary warning) I choose to substituite it with nanoid as pointed out in [this issue](https://github.com/adamgibbons/ics/issues/182).
All tests are ok

moving away from uuid and toward nanoid

---

README.md
index.d.ts
src/pipeline/build.js
src/pipeline/format.js
src/schema/index.js
test/pipeline/build.spec.js
test/pipeline/format.spec.js
test/schema/index.spec.js

Using `X-ALT-DESC;FMTTYPE=text/html` attribute in ICS i added support for adding html content to the ICS file. It was discussed here: https://github.com/adamgibbons/ics/issues/119

Support for html content

---

src/utils/set-organizer.js

Hi there:)
I had a chance to work with your library and found that users with dir property aren't added as attendees to the native mac os calendar. So I've found that there is a missing quote. 
According to the [DIR RFC](https://datatracker.ietf.org/doc/html/rfc5545#section-3.2.6) the dir format should be next:
`dirparam   = "DIR" "=" DQUOTE uri DQUOTE`
For example: 
`ORGANIZER;DIR="ldap://example.com:6666":mailto:jimdo@example.com`
So I started to play with generated ics files and it was confirmed. When I add quotes I can see invitees, when remove I can't
- Wrap dir URI with quotes according to the specification.
- There are no possible regressions because this is done according to the rfc. Some clients can work without quotes but some of them can't, so this change will only improve the …

Fix DIR format according to the RFC-5545

---

index.d.ts
src/pipeline/format.js

I owe a lot to this module as it made my last big project at my day job possible. But I was hampered by two issues with simple solutions. I knew I had to fix them.
_By the way, this is my first public contribution via PR on GitHub. My first-time is long overdue. 😅_
First is #210 - where Outlook stops parsing after encountering `BEGIN:VALARM`. Thus, `RRULE:` and `DURATION:` will be ignored.
Here's a video demonstration of this issue. Simply re-ordering some lines fixes Outlook import.
https://user-images.githubusercontent.com/2433505/185986308-e79aa6c6-612e-40b7-9c41-dc7bbfb6505a.mp4
Second is #205 where the type definitions lack three properties for the `Alarm` type. I simply added these in, matching the behavior you find in `setAlarm()`.
I personally only needed `description`, but knew I …

Alarm fix for Outlook (#210) and added missing types Alarm (#205)

---

package-lock.json
src/pipeline/build.js
src/pipeline/format.js
test/pipeline/build.spec.js

Setting the `sequence` property to the number `0` results in a created event that doesn't have `SEQUENCE`.
The reason for this is that the library removes falsey values from the ICS file, and `0` is a falsey value.
This PR addresses the issue by removing `undefined` values instead of falsey values.

Sequence zero bug

---

README.md

I think this would save people some time for very little effort — I got tripped up by expecting `ics` to be the default export.

Add ESM usage example

---

src/utils/format-date.js
test/utils/format-date.spec.js

Remove the default second value because when you send an event request and an event cancel in the same second, Google Calendar omits event cancel.

Remove 00 like default second value

---

src/index.js
test/index.spec.js

Right now, `createEvents` will return `{error: null, value: null}` with 0 events. This is impractical, because IMO it is a common use case to server a calendar feed with 0 events (e.g. no upcoming events, or all cancelled/removed).
This PR changes `createEvents` to return an empty (but valid) calendar feed in this case. Strictly speaking, this is a breaking change.

createEvents: return iCal string with 0 events

---

index.js
package.json

TypeScript 4.7 introduced the `node16` module resolution. This is more strict, and more correct than older module resolution options.
According to TypeScript, before this change it is possible to use `require('ics')`, but not `import 'ics'` from native ESM. This is because there is an explicit `require` export, that is accompanied by a `.d.ts` file, but there’s also a default export, which is untyped.
This change fixes it by removing `index.js` altogether. Its only purpose was to re-export everything from `dist/index.js`. This is now handled by pointing the main entrypoint and the default export in `package.json` to `dist/index.js`. The `types` export is necessary, because the file doesn’t exist in the same place as the dist files.
The `module` option was removed entirely. This is a faux …

Fix exports in package.json

---

package-lock.json
package.json
src/schema/index.js

First of all thanks @adamgibbons for your great opensource package!
We are currently using your package in our application, however we have run into a problem with a possible optimization bailouts due to a non ES downstream dependency of the yum dependency of your package ( ics -> yup -> lodash ). Since yup phased out lodash since their v1.0 release this can now be solved for us by updating the yup dependency in your package :) . Hence this PR
There was only one breaking change `options.path` in the dateTimeSchema now returns a none indexed string (so `start` instead of `start[1]`) so we can no longer extract the index from that and have to use indexOf to get the index using the value.
There should be no failing tests, however since I used a newer version of npm to update the package, it …

Updated yup to ^1.2.0 and fixed breaking change

---

index.d.ts
src/schema/index.js
src/utils/set-contact.js
test/pipeline/format.spec.js
test/pipeline/validate.spec.js
test/utils/set-contact.spec.js

this is a tweak of PR #237 with the following updates:
* change the schema so that xNumGuests is a number
* restrict SEQUENCE to the max for an integer, per [RFC 5545](https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.7.4) (I have found that if it is larger than the signed int max, gmail will ignore it)
* RSVP should be optional (only use it if it is specified to be true or false)
* add some tests for the new fields

CUTYPE and X-NUM-GUESTS support

---

src/utils/set-alarm.js
test/utils/set-alarm.spec.js

`setTrigger` already handles it.
Fixes #263

Remove accidental `encodeNewLines`

---

index.d.ts

This PR corrects the TypeScript type for the `exclusionDates` property on the `EventAttributes` object. As far as I can tell from looking in `schema/index.js`, all the regular date time formats should be also be valid in the `exclusionDates` array. I was able to successfully use `DateArray`s in an `exclusionDates` array for a project after adding a `// @ts-ignore` directive.
Thanks for maintaining the project!

Use `DateTime` type for event exclusion dates
