README.md, ex/app.js, ex/public/created/example.ics, ex/public/index.html, lib/cal-event.js, package.json, test/cal-event.spec.js
Added Attendees with test case & Expressjs example with a readme update
=> Added Attendees & Expressjs Example

lib/cal-event.js
Hi guys,
While working with your package which helped me a lot, I faced one little problem is that I cant specific the time zone while generating the ics file, and according to this [SO ](http://stackoverflow.com/questions/7626114/ics-timezone-not-working) answer, I made a litlle edit to your package.
Thx
=> Add timezone specification feature

ex/app.js
Update the example to instantiate the ics object, add a missing bracket in an object
=> Fix missing bracket, instantiate new ics object in example

README.md, lib/ics.js, package.json, test/ics.spec.js
I followed the basic rules for requirements from the spec here: https://icalendar.org/iCalendar-RFC-5545/3-6-6-alarm-component.html
There is more work that can be done to follow all of the detailed requirements.
=> Add support for alarms and follow basic rules in spec

src/utils/set-alarm.js, test/pipeline/format.spec.js, test/utils/set-alarm.spec.js
alarm not triggered when action is in small case
=> Alarm action in upper case fix

src/schema/index.js, src/utils/set-alarm.js
alarm trigger should support negative durations, i.e. "before" an event
=> alarm trigger changes

src/utils/format-text.js, src/utils/set-description.js, src/utils/set-summary.js, test/pipeline/format.spec.js
update text type escaping to match rfc
add and update tests
closes #67
=> fix escaping of characters in TEXT properties

README.md, src/pipeline/build.js, src/pipeline/format.js, src/schema/index.js, test/pipeline/build.spec.js, test/pipeline/format.spec.js
Addressed the comments from review of #80 .
Fixes #64
=> Add sequence attribute -- updated

README.md
As requested in https://github.com/adamgibbons/ics/pull/87#issuecomment-430708012
=> Add DIR field examples in README

package.json, src/schema/index.js, test/schema/index.spec.js
Fixes https://github.com/adamgibbons/ics/issues/103
=> add summary to schema

README.md, package.json, src/pipeline/build.js, src/pipeline/format.js, src/schema/index.js, test/index.spec.js, test/pipeline/build.spec.js, test/pipeline/format.spec.js, test/schema/index.spec.js
Add support for `CREATED` and `LAST-MODIFIED` attributes
closes #136
=> support created, lastModified vcal props

README.md, index.d.ts, src/pipeline/build.js, src/pipeline/format.js, src/schema/index.js, test/pipeline/build.spec.js, test/pipeline/format.spec.js, test/schema/index.spec.js
Add a `X-WR-CALNAME` field to mean the name of the calendar extended by Apple.
Resolve #123
=> Support X-WR-CALNAME

src/pipeline/format.js, src/utils/index.js, src/utils/set-location.js, test/pipeline/format.spec.js
The location field needs to format the "comma" as well, otherwise it does not work properly on macOS Calendar app
=> Format location

README.md
=> Enable syntax highlighting for example 4

index.d.ts
Adds missing definition for typescript
=> Adds missing busyStatus typescript definition

.gitignore, README.md, src/schema/index.js, src/utils/fold-line.js, src/utils/format-date.js, src/utils/set-alarm.js, test/pipeline/build.spec.js, test/pipeline/format.spec.js, test/schema/index.spec.js
=> Revert "Added support for dir value for organizer - for PR 132"

index.d.ts, src/index.js
A new util function is created to convert from unix timestamp to DateArray format
Eg: ics.convertTimestampToArray(1628752185560) -> [ 2021, 8, 12, 12, 39 ]
=> Added a util function to convert from unix timestamp to DateArray

README.md
Documentation update related to: https://github.com/adamgibbons/ics/pull/192
=> Update readme to reflect change from uuid to nanoid

package.json
Adds ESM support by correcting ESM package configuration, fixing https://github.com/adamgibbons/ics/issues/188 which was wrongfully closed
=> Fix incorrect ESM exportation

README.md
Move closing curly brace and parenthesis next to the function they close and before the sample output to make it easier to copy-paste the code sample.
The instinctive behavior of many developers (myself included) trying this code for themselves would be to copy the code all the way to the start of the sample output and not notice the closing curly and parenthesis triggering a syntax error.
=> Update first sample code snippet in README.md

src/schema/index.js
Clarified error message to help in debugging.
This is clarified in the API docs but not in the error message.
=> Made error message for DTEND and DURATION clearer

test/pipeline/format.spec.js
The input needs to be the local time, and internally it gets converted to utc time, so I was using the wrong date fns.
Does it work for you now?
=> Fix exception date-time test

src/utils/fold-line.js
```js
const event = ICS.createEvent({
start: [2018, 5, 30, 6, 30],
duration: { hours: 6, minutes: 30 },
title: "Bolder Boulder",
description: "Annual 10-kilometer run in Boulder, Colorado",
location: "Folsom Field, University of Colorado (finish line)",
url: "http://www.bolderboulder.com/",
geo: { lat: 40.0095, lon: 105.2669 },
categories: ["10k races", "Memorial Day Weekend", "Boulder CO"],
status: "CONFIRMED",
busyStatus: "BUSY",
organizer: { name: "Admin", email: "Race@BolderBOULDER.com" },
attendees: [
{
name: "Adam Gibbons",
email: "adam@example.com",
rsvp: true,
partstat: "ACCEPTED",
role: "REQ-PARTICIPANT",
},
{
name: "Brittany Seaton",
email: "brittany@example2.org",
dir: "https://linkedin.com/in/brittanyseaton",
role: "OPT-PARTICIPANT",
},
],
});
if (event.error) { …
```
=> Fix error with runes lib

src/index.js, src/pipeline/index.js, src/schema/index.js, test/index.spec.js
Exposing a method that runs the URL regex, so it can be checked before running `createEvent` for validation.
=> add url validation public method
